theme: jekyll-theme-midnight

# Name of website
title: SlickFlick (Web app)

# Your name to show in the footer
author: Amrit Sandhu




# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: /media/titlePicSlickFlick.jpeg



